[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run start"
  port = 3000
  targetPort = 3000
  publish = "public"
  autoLaunch = true
